server.port=9001

spring.websocket.timeouts.send-timeout=600000
spring.websocket.timeouts.connect-timeout=600000
spring.websocket.timeouts.disconnect-timeout=600000
logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging.simp=DEBUG
